[tool.poetry]
name = "data-structures-algorithms"
version = "0.1.0"
description = ""
authors = ["yxtay <wyextay@gmail.com>"]

[tool.poetry.dependencies]
python = "3.7"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.8.3"
isort = "^4.3.21"
jupyterlab = "^2.1.5"
mypy = "^0.782"
poetry = "^1.0.9"
pre-commit = "^2.5.1"
pytest = "^5.2"
pytest-cov = "^2.10.0"

[tool.black]
line-length = 100
target-version = ["py37"]
include = ".pyi?$"
exclude = """
(
  /(
      .eggs         # exclude a few common directories in the
    | .git          # root of the project
    | .hg
    | .mypy_cache
    | .tox
    | .venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
"""

[tool.isort]
# compatible with psf/black
# https://github.com/psf/black/blob/master/docs/compatible_configs.md
force_grid_wrap = 0
include_trailing_comma = true
line_length = 100
multi_line_output = 3
not_skip = "__init__.py"
use_parentheses = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
